inserindo debug

diff --git a/Dockerfile.processor b/Dockerfile.processor
--- a/Dockerfile.processor
+++ b/Dockerfile.processor
@@ -1,6 +1,6 @@
 FROM joaca/iped:dependencies
 
-ARG SNAPSHOT=true IPED_RELEASE_VERSION=4.3.0 SNAPSHOT_WORKFLOW_ID=28458905937 PKGTMPDIR=/tmp/pkgs
+ARG SNAPSHOT=true IPED_RELEASE_VERSION=4.3.0 SNAPSHOT_WORKFLOW_ID=28046804277 PKGTMPDIR=/tmp/pkgs
 
 RUN --mount=type=secret,id=ACTION_GH_TOKEN export ACTION_GH_TOKEN=$(cat /run/secrets/ACTION_GH_TOKEN) \
     && mkdir -p /opt/IPED/ && cd /opt/IPED/ \
@@ -17,6 +17,7 @@ RUN --mount=type=secret,id=ACTION_GH_TOKEN export ACTION_GH_TOKEN=$(cat /run/sec
                             https://api.github.com/repos/sepinf-inc/IPED/actions/artifacts  | \
                           jq --arg workflow_id $SNAPSHOT_WORKFLOW_ID -c '.artifacts[] | select(.workflow_run.id|tostring == $workflow_id) | .archive_download_url' | \
                         tr -d '\"') && \
+            if [ -z "$snapshotURL" ]; then echo "ERRO CRITICO: Artefato expirado ou Token invalido! URL de download do snapshot veio vazia." && exit 1; fi && \
             echo "Downloading ${snapshotURL}..." && \
             curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${ACTION_GH_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" --output ${PKGTMPDIR}/iped.zip ${snapshotURL} && \
             unzip -p ${PKGTMPDIR}/iped.zip | tar -xvz --strip-components=1; \
